USE [master]
GO
/****** Object:  Database [CORE_3CRUD]    Script Date: 06/07/2021 11:37:49 ******/
CREATE DATABASE [CORE_3CRUD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CORE_3CRUD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.RGATILANOV\MSSQL\DATA\CORE_3CRUD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CORE_3CRUD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.RGATILANOV\MSSQL\DATA\CORE_3CRUD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [CORE_3CRUD] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CORE_3CRUD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CORE_3CRUD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET ARITHABORT OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CORE_3CRUD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CORE_3CRUD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CORE_3CRUD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CORE_3CRUD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET RECOVERY FULL 
GO
ALTER DATABASE [CORE_3CRUD] SET  MULTI_USER 
GO
ALTER DATABASE [CORE_3CRUD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CORE_3CRUD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CORE_3CRUD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CORE_3CRUD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CORE_3CRUD] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CORE_3CRUD', N'ON'
GO
ALTER DATABASE [CORE_3CRUD] SET QUERY_STORE = OFF
GO
USE [CORE_3CRUD]
GO
/****** Object:  Table [dbo].[users]    Script Date: 06/07/2021 11:37:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[user_id] [int] IDENTITY(1,1) NOT NULL,
	[user_name] [varchar](250) NULL,
	[user_lastname] [varchar](250) NULL,
	[user_nick] [varchar](250) NULL,
	[user_password] [varchar](256) NULL,
	[user_createdate] [date] NULL,
	[user_status] [bit] NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [CORE_3CRUD] SET  READ_WRITE 
GO
